GUI
Tomahawkd/Netfilter-Firewall pull request #12
Opened 2019-05-26 10:03 UTC by Vshows

ui

2019-05-26 10:04 UTC, Vshows commented
gui

2019-05-26 12:11 UTC, Tomahawkd requested changes
potential bugs and features required

2019-05-26 12:11 UTC, Tomahawkd commented on gui/mainwindow.cpp
> +    string filename = "/home/Vshows/test" ;
what happens if file does not exist?

2019-05-26 12:11 UTC, Tomahawkd commented on gui/mainwindow.cpp
> +        ofs<<ip_text;
what about deleted rules?

2019-05-26 12:11 UTC, Tomahawkd commented on gui/mainwindow.cpp
> +        string ip_text = ip_ori_text + "-"+ip_des_text+"\n";
format should be: address/mask:port(optional, default:all)

2019-05-26 12:11 UTC, Tomahawkd commented on gui/mainwindow.cpp
> +void MainWindow::write_filter(){
read rules also needed

2019-05-26 12:24 UTC, Tomahawkd requested changes
add requirement

2019-05-26 12:24 UTC, Tomahawkd commented on gui/mainwindow.cpp
> +    string filename = "/home/Vshows/test" ;
rule address: /var/netfilter/rules

2019-05-27 05:22 UTC, Vshows commented
UI2.0

2019-05-27 06:14 UTC, Tomahawkd commented
Now the gui is complete, waiting for file operation completion to merge

2019-05-27 14:01 UTC, closed without merging